server {
    listen 80;
    server_name taskmarket.space www.taskmarket.space;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name taskmarket.space www.taskmarket.space;
    root /app/web;
    index index.php;

    ssl_certificate /etc/letsencrypt/live/taskmarket.space/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/taskmarket.space/privkey.pem;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ \.php$ {
        return 404;
    }

    error_log /app/.docker/log/error.log;
    access_log /app/.docker/log/access.log;
}
